-- MySQL Script generated by MySQL Workbench
-- Sat Mar 23 18:10:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MayaMarketBD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MayaMarketBD` ;

-- -----------------------------------------------------
-- Schema MayaMarketBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MayaMarketBD` DEFAULT CHARACTER SET utf8 ;
USE `MayaMarketBD` ;

-- -----------------------------------------------------
-- Table `MayaMarketBD`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MayaMarketBD`.`User` ;

CREATE TABLE IF NOT EXISTS `MayaMarketBD`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `dpi` BIGINT UNSIGNED NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `profile` VARCHAR(100) NULL DEFAULT 'http://localhost:3000/img/profiles/default.jpeg',
  `coins` DOUBLE NULL DEFAULT 0,
  `money` DOUBLE NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `dpi_UNIQUE` (`dpi` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MayaMarketBD`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MayaMarketBD`.`Image` ;

CREATE TABLE IF NOT EXISTS `MayaMarketBD`.`Image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(200) NOT NULL,
  `FK_User` INT NOT NULL,
  `FK_Publication` INT NULL,
  PRIMARY KEY (`id`, `FK_User`),
  INDEX `fk_Image_User1_idx` (`FK_User` ASC) VISIBLE,
  CONSTRAINT `fk_Image_User1`
    FOREIGN KEY (`FK_User`)
    REFERENCES `MayaMarketBD`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MayaMarketBD`.`Publication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MayaMarketBD`.`Publication` ;

CREATE TABLE IF NOT EXISTS `MayaMarketBD`.`Publication` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  `isVolunteering` TINYINT NOT NULL,
  `priceM` DOUBLE NOT NULL,
  `priceCP` DOUBLE NOT NULL,
  `isSold` TINYINT NOT NULL DEFAULT 0,
  `isApproved` VARCHAR(45) NOT NULL DEFAULT 0,
  `quantity` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `FK_User` INT NOT NULL,
  PRIMARY KEY (`id`, `FK_User`),
  INDEX `fk_Publication_User1_idx` (`FK_User` ASC) VISIBLE,
  CONSTRAINT `fk_Publication_User1`
    FOREIGN KEY (`FK_User`)
    REFERENCES `MayaMarketBD`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MayaMarketBD`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MayaMarketBD`.`Tag` ;

CREATE TABLE IF NOT EXISTS `MayaMarketBD`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTag`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MayaMarketBD`.`TagsOfPublication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MayaMarketBD`.`TagsOfPublication` ;

CREATE TABLE IF NOT EXISTS `MayaMarketBD`.`TagsOfPublication` (
  `FK_Publication` INT NOT NULL,
  `FK_Tag` INT NOT NULL,
  PRIMARY KEY (`FK_Publication`, `FK_Tag`),
  INDEX `fk_Publication_has_Tag_Tag1_idx` (`FK_Tag` ASC) VISIBLE,
  INDEX `fk_Publication_has_Tag_Publication1_idx` (`FK_Publication` ASC) VISIBLE,
  CONSTRAINT `fk_Publication_has_Tag_Publication1`
    FOREIGN KEY (`FK_Publication`)
    REFERENCES `MayaMarketBD`.`Publication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publication_has_Tag_Tag1`
    FOREIGN KEY (`FK_Tag`)
    REFERENCES `MayaMarketBD`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MayaMarketBD`.`TagOfUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MayaMarketBD`.`TagOfUser` ;

CREATE TABLE IF NOT EXISTS `MayaMarketBD`.`TagOfUser` (
  `FK_Tag` INT NOT NULL,
  `FK_Use` INT NOT NULL,
  PRIMARY KEY (`FK_Tag`, `FK_Use`),
  INDEX `fk_Tag_has_User_User1_idx` (`FK_Use` ASC) VISIBLE,
  INDEX `fk_Tag_has_User_Tag1_idx` (`FK_Tag` ASC) VISIBLE,
  CONSTRAINT `fk_Tag_has_User_Tag1`
    FOREIGN KEY (`FK_Tag`)
    REFERENCES `MayaMarketBD`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tag_has_User_User1`
    FOREIGN KEY (`FK_Use`)
    REFERENCES `MayaMarketBD`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
